<a href="https://colab.research.google.com/github/XimeeeRJ/THC-XRJ/blob/Tareas/Clase_9_THC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [5]:
print(arr[:4])

[1 2 3 4]


In [7]:
print(arr[4:])

[5 6 7]


In [6]:
print(arr[-3:-1])

[5 6]


In [9]:
#Ultimo elemento
print(arr[-1])

7


In [10]:
print(arr[1:5:2])

[2 4]


In [14]:
print(arr[::6])

[1 7]


In [16]:
print(arr[0:])

[1 2 3 4 5 6 7]


In [17]:
print(arr[:0])

[]


In [3]:
arr = np.array([7,8,9,1,5,11,29])
print(arr[1:7])

[ 8  9  1  5 11 29]


In [18]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,2:3])

[3]


In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,:])

[1 2 3 4 5]


In [25]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1, 2])

[3]


In [28]:
#Ejercicio

x = np.array([1,2,3])
y = np.array([4,5,6])

suma = x+y
resta = x-y
multiplicacion = x*y
division = x/y

print("La suma es", suma)
print("La resta es", resta)
print("La multiplicación es", multiplicacion)
print("La división es", division)

La suma es [5 7 9]
La resta es [-3 -3 -3]
La multiplicación es [ 4 10 18]
La división es [0.25 0.4  0.5 ]


In [29]:
angulos = np.array([0, np.pi/2, np.pi])
coseno = np.cos(angulos)
print("Los cosenos", coseno)
print("De los angulos", angulos)

Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
De los angulos [0.         1.57079633 3.14159265]


In [30]:
x = np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [31]:
matriz = x.reshape(2,4)
matriz


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
matriz = x.reshape(4,2)
matriz


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:

numero = input("ingrese un numero del 1 al 10 = ")
np.random.randint(0,10,size=1)
while i < 5:
  if numero ==
