<a href="https://colab.research.google.com/github/XimeeeRJ/THC-XRJ/blob/Tareas/Clase_8_THC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Arreglos**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Segundo elemento de la primera fila", arr[0,1])

Segundo elemento de la primera fila 2


# Matrices

In [12]:
#Suma de elementos de una matriz con listas.

A = [[1,2,3], [4,5,6], [7,8,9]]
suma = 0

for i in range(len(A)):
  for j in range(len(A)):
   suma += A[i][j]

print(suma)

45


In [ ]:
#Suma de elementos de una matriz con numpy.

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
suma = 0

for i in range(len(A)):
  for j in range(len(A)):


print(suma)


45


In [13]:
#Producto escalar por renglones

import numpy as np

def PP(a,b):
  PP = 0
  for i in range(len(a)):
    PP += a[i]*b[i]
  return PP




In [14]:
from types import prepare_class
arr2=np.array([[1,2,3], [4,5,6], [1,1,1]])
arr3=np.array([[1,1,1], [1,1,1], [1,1,1]])
PP_por_reng=np.array([0,0,0])
PP_por_col=np.array([0,0,0])

for i in range(len(arr2)):
  PP_por_reng[i]=PP(arr2[i],arr3[i])

PP_por_reng

array([ 6, 15,  3])

In [17]:
def agarracol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])
  return np.array(nuevo)


In [18]:
col1= agarracol(arr2, 0)
col1

array([1, 4, 1])

In [19]:
for i in range(len(arr)):
  PP_por_col[i]=PP(agarracol(arr2,i),agarracol(arr3,i))

PP_por_col

array([6, 8, 0])