<a href="https://colab.research.google.com/github/XimeeeRJ/THC-XRJ/blob/Tareas/Tarea_Examen_THC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tarea Examen**

Alumnas:

*   Paulina Ramos Reyes
*   Ximena Rodríguez Jaramillo




Ejercicio 1. Sumas de matrices rectangulares.

In [3]:
import numpy as np

In [4]:
#Creacion de dos matrices con numpy
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
#Creamos la matriz c del tamaño de arr1 con ceros
C = np.zeros_like(arr1)

#For's para las filas y columnas de las matrices arr1 y arr2
for i in range (len(arr1)):
  for j in range(len(arr1)):

      #Suma de los elementos de las matrices arr1 y arr2 y se guarda en la matriz C
      C[i][j] = (arr1[i][j] + arr2[i][j])

print("A=")
print(arr1[0:3, 0:3])
print("B=")
print(arr2[0:3, 0:3])
print(f"La suma de matrices es")
print(C)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
[[10 11 12]
 [13 14 15]
 [16 17 18]]
La suma de matrices es
[[11 13 15]
 [17 19 21]
 [23 25 27]]


Ejercicio 2. Multiplicación entrada a entrada rectangulares.

In [5]:
#Creacion de las matrices arr1 y arr2
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
#creamos la matriz C de tamaño arr1
C = np.zeros_like(arr1)

#For's para las columnas y filas de las matrices arr1 y arr2
for i in range (len(arr1)):
  for j in range(len(arr1)):
    #Multiplicacion de los elementos de arr1 y arr2 y el resultado se guarda en la mtriz C.
    C[i][j] = (arr1[i][j] * arr2[i][j])

print("A=")
print(arr1[0:3, 0:3])
print("B=")
print(arr2[0:3, 0:3])
print(f"La multiplicación de matrices es")
print(C)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
[[10 11 12]
 [13 14 15]
 [16 17 18]]
La multiplicación de matrices es
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


Ejercicio 3. La traza.

In [6]:
#Creacion de la matriz con numpy
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Creamos la variable dondde se guardar la suma de la diagonal principal
traza = 0

#For para las filas y columnas de la matriz
for i in range(len(arr1)):
    #suma de los elementos de la diagonal principal
    traza += arr1[i][i]

print("A=")
print(arr1)
print(f"La traza de la matriz A es", traza)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La traza de la matriz A es 15


Ejercicio 4. La transpuesta de una matriz.

In [7]:
#Definir la matríz A
A = [[1,2,3], [4,5,6], [7,8,9]]

#Creación de la función para crear la transpuesta de la matríz A
def transpuesta(A):
  #Creamos una nueva matríz, que sera la matríz transpuesta.
  A_Trans = []

  #Creación de filas para la matríz transpuesta.
  for _ in range(len(A)):
    A_Trans.append([])

  #Acceder a las columnas y filas de la matríz A (Matríz original)
  for i in range(len(A)):
    for j in range(len(A)):
      #Agregar el eleemto A[i][j] a la matríz transpuesta.
      A_Trans[j].append(A[i][j])

  #Regresar la matríz transpuesta
  return A_Trans

#Llamar a la función
A_Trans = transpuesta(A)


print("Matríz original", A)
print("Matríz transpuesta", A_Trans)

Matríz original [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Matríz transpuesta [[1, 4, 7], [2, 5, 8], [3, 6, 9]]


Ejercicio 5.
El máximo y mínimo elemto de una matriz

In [8]:
#Definir la matriz A
A = [[1,2,3], [4,5,6], [7,12,9]]

#Creamos las variables donde se guardaran el valor mínimo y máximo
Max = A[0][0]
Min = A[0][0]

#Acceder a las columnas y filas de la matríz
for i in range(len(A)):
  for j in range(len(A)):

    #Comparar los elementos, el elemento que se concidera como máximo con el elemento actual
    if A[i][j] > Max:
        Max = A[i][j]
    #Comparar los elementos, el elemento que se concidera como mínimo con el elemento actual
    if A[i][j] < Min:
        Min = A[i][j]


print("El valor máximo de la matríz es = ", Max)
print("El valor mínimo de la matríz es = ", Min)

El valor máximo de la matríz es =  12
El valor mínimo de la matríz es =  1


Ejercicio 6. La suma del cuadrado de los elementos de una matriz.

In [9]:
#Definir la matriz A
A = [[1,1,1], [1,1,1], [1,1,1]]

#Variable en la que se guardara la suma de los elementos de la matríz
suma_cuadrados = 0

#Filas de la matríz
for i in range(len(A)):

  #Columnas de la matríz
  for j in range(len(A)):

    #Calcular la suma de los cuadrados de los elementos de la matríz
    suma_cuadrados += A[i][j] ** 2


print("La suma de los cuadrados de los elementos de la matríz, es:", suma_cuadrados)

La suma de los cuadrados de los elementos de la matríz, es: 9


Ejercicio 7. La potencia de matrices

In [10]:
#Definir la matríz A
A = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
#Crear la variable n para el valor de la potencia
n = 2

#Crear la función para poder hacer la potencia
def pot_mat(A, n):
  resultado = A

  #Multiplicamos la matríz por si misma n-1 veces
  for _ in range(n - 1):
    A_elev = []
    for i in range(len(A)):
      fila = []
      for j in range(len(A)):
        #Calcular la potencia de cada elemento
        fila.append(sum(A[i][k] * resultado[k][j] for k in range(len(A))))
      A_elev.append(fila)
    resultado = A_elev

  return resultado

#Mandar llamar a la función
resultado = pot_mat(A, n)
print("Matríz original", A)
print("Matriz elevada al valor de n", resultado)

Matríz original [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
Matriz elevada al valor de n [[3, 3, 3], [3, 3, 3], [3, 3, 3]]
